<?php


namespace app\api\controller;


use think\Exception;

class AuthBase extends ApiBase
{
    public $access_token = null;
    public $username = null;
    public $user_id = null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->access_token = $this->request->header('access-token');
        if (empty($this->access_token) || !$this->isLogin($this->access_token)) {
//            echo 22;
//            return show(config('status.not_login'),'not login');
            throw new Exception('not login',config('status.not_login'));
        }
    }

    public function isLogin($access_token)
    {
        $user_info = cache(config('redis.token_pre').$access_token);
//        var_dump($user_info);die;
        if (!isset($user_info['username']) || empty($user_info['username']) || empty($user_info['user_id'])) {
            return false;
        }
        $this->username = $user_info['username'];
        $this->user_id = $user_info['user_id'];
        return true;
    }

}